### ISSUE TITLE
Pickle problem

### ISSUE THREAD

**Issue by ZubicarayG** [NeuroAI-HD/HD-BM#2]
Hello,

I get the following error when trying to run either hd_bm_predict or hd_bm_slim_predict on Mac OS Ventura:

starting prediction...
Traceback (most recent call last):
  File "/opt/fsl/bin/hd_bm_slim_predict", line 8, in <module>
    sys.exit(main())
  File "/opt/fsl/lib/python3.10/site-packages/hd_bm/hd_bm_slim_predict.py", line 93, in main
    predict_cases(
  File "/opt/fsl/lib/python3.10/site-packages/nnunet-1.7.0-py3.10.egg/nnunet/inference/predict.py", line 206, in predict_cases
    for preprocessed in preprocessing:
  File "/opt/fsl/lib/python3.10/site-packages/nnunet-1.7.0-py3.10.egg/nnunet/inference/predict.py", line 109, in preprocess_multithreaded
    pr.start()
  File "/opt/fsl/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/fsl/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/fsl/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/opt/fsl/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/fsl/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/fsl/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/fsl/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x2270184c0>: attribute lookup <lambda> on nnunet.utilities.nd_softmax failed

I'm hoping you might be able to suggest a workaround?

thanks,

Greig

**Comment by ZubicarayG** [comment]
Help again,

I should add that I have HD-BET working in CPU mode and have been trying to replace CUDA with Apple's tensor flow, but without much success. I might try finding a lInux box!

thanks,

Greig

**Comment by FabianIsensee** [comment]
Hey, does it work in a native Linux environment or does this bug only appear on Apple?

**Comment by ZubicarayG** [comment]
Yes, it works in native Linux. This was only appearing in Apple.

**Comment by FabianIsensee** [comment]
I do not have a mac. In fact I have never used one in my life. So I cannot really analyze and fix this issue :-/

**Comment by TaWald** [comment]
Hey @ZubicarayG,
could you specify which kind of Mac you have? Is it a M1/M2 mac or an intel one?

**Comment by TaWald** [comment]
Closing due to inactivity
